### ISSUE TITLE
[space-station-os.github.io] Design structure / table of contents

### ISSUE THREAD

**Issue by yuyuqq** [space-station-os/space-station-os.github.io#1]
### User Story: 
- Define website structure in space-station-os.github.io.**

### Acceptance Criteria:
- The home navigation menu prospectively includes links to sites, describing concept, installation, demos, prospective demos, integration, how to join, and any other necessary sites.
- The site structure follows a clear and logical hierarchy.
- Each page has a consistent header and footer design.

### Acceptance Criteria:
- Approved by demo

**Comment by Ohara124c41** [comment]
Initial redesign has been structured, but it appears some javascript details are not rendering (proper dropdown icons, text inline (side of) main content). Was built locally with vs code and live server, so I will update once I find the issue and work around.
