### ISSUE TITLE
[space-station-os.github.io] Prepare for prospective demos

### ISSUE THREAD

**Issue by yuyuqq** [space-station-os/space-station-os.github.io#2]
### User Story:
- By reading prospective demos, the prospective contributers can _imagine_ what to contribute in demos. The description should be of appropriate depth 
- Found in space-station-os.github.io.

### Acceptance Criteria:
- 6 (TBD) prospective demos are shared on the web.
- Feedback for depth of description is received.

**Comment by Ohara124c41** [comment]
https://space-station-os.github.io/demos.html

**Comment by yuyuqq** [comment]
Restructured GitHub project to accept demos. Done.
