### ISSUE TITLE
[DemoX] Prepare for ECLSS demo

### ISSUE THREAD

**Issue by yuyuqq** [space-station-os/space-station-os.github.io#7]
### User Story:
- We know we have a potential user for ECLSS on SSOS. We prepare for the simulation, demo at first.
### Acceptance Criteria:
- What to simulate is identified
- What could be simulated is idenfied 
- Document it on space-station-os.github.io

**Comment by siddarth09** [comment]
https://docs.google.com/document/d/1e0iuG-e3bj8xFaQQypPAE-KxrJ69jMfB8pwMludQxHM/edit?usp=sharing


Updated this with a small report on my findings of the system. After discussing with @yuyuqq on December 18th.

**Comment by siddarth09** [comment]
I have  created a small simulation for Air revitalization system https://github.com/space-station-os/space_station_eclss/tree/patch-1, 

- Create a GUI using python 
- unit testing 
- start working on water recovery system and oxygen generation system

**Comment by yuyuqq** [comment]
@siddarth09 Thank you, I finally had time to review space_station_eclss. It is a definatively good, meaningful start.  

I think we met the acceptance criteria for all.

Let us define a next goal. Close.
